version: "3.9"
services:
  database:
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    image: postgres:15.2

  webapi:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: webapi
    ports:
      - "8080:8080"
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_HOST=database
        - POSTGRES_PORT=5432
        - POSTGRES_DB=postgres
        - SERVER_PORT=8080


  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    environment:
      SERVER_URL: http://host.docker.internal:8080
      STAGE: all
      # all - запуск всех тестов из трёх доступных этапов
      # 0, 1 или 2 - запуск тестов для соответствующего этапа